# This is a basic workflow to help you get started with Actions

name: Tag based release 

# Controls when the workflow will run
on:
  pull_request:
    types: [ labeled ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event.label.name == 'bug' }}
    runs-on: ubuntu-latest
  name: Run CodeBuild
      uses: aws-actions/aws-codebuild-run-build@v1
      with:
        project-name: api-dev
        buildspec-override: buildspec.yml


